server:
  port: 8001

spring:
  application:
    name: AUTH-SERVICE

  # Database
  datasource:
    url: jdbc:mysql://storage-service/ms_arch?createDatabaseIfNotExist=true
    username: malware
    password: userpassword
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    open-in-view: false
    generate-dll: true
    hibernate:
      ddl-auto: update

  # Distributed Locking & caching
  redis:
    host: caching-service
    port: 6379

  # Distributed tracing
  sleuth:
    enabled: ${TRACING_ENABLED:false}
  zipkin:
    baseUrl: http://tracing-service:9411/

