secret: "soem"


server:
  port: ${SERVER_PORT:8002}

spring:
  # Database
  datasource:
    url: jdbc:mysql://localhost:3306/ms_arch?createDatabaseIfNotExist=true
    username: user
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    open-in-view: false
    generate-dll: true
    hibernate:
      ddl-auto: update

  # Distributed Locking & caching
  redis:
    host: localhost
    port: 6379

  # Distributed tracing
  sleuth:
    enabled: ${TRACING_ENABLED:false}
  zipkin:
    baseUrl: http://localhost:9411/

  cloud:
    # Service discovery
    consul:
      enabled: ${DISCOVERY_ENABLED:false}
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${random.int[1,999999]}

# Health check endpoints
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

# Resilience
resilience4j:
  retry:
    instances:
      productService:
        maxRetryAttempts: 3
        waitDuration: 2s