server:
  port: 8001

spring:
  application:
    name: AUTH-SERVICE

  # Database
  datasource:
    url: jdbc:mysql://storage-service/ms_arch?createDatabaseIfNotExist=true
    username: malware
    password: userpassword
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    generate-dll: true
    hibernate:
      ddl-auto: update

  # Distributed tracing
  sleuth:
    enabled: ${TRACING_ENABLED}
  zipkin:
    baseUrl: http://tracing-service:9411/

