spring:
  application:
    name: AUTHSERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/ms_arch?createDatabaseIfNotExist=true
    username: terareum
    password: Terareum@2023
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    generate-dll: true
    hibernate:
      ddl-auto: update

server:
  port: 8001
