server:
  port: 6001

spring:
  application:
    name: AUTH-SERVICE

  # Database
  datasource:
    url: jdbc:tc:mysql:8.0//ms_arch_test?createDatabaseIfNotExist=true
    username: user
    password: pass_word
    driverClassName: org.testcontainers.jdbc.ContainerDatabaseDriver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    open-in-view: false
    generate-dll: true
    hibernate:
      ddl-auto: update

  # Distributed Locking & caching
  redis:
    host: localhost
    port: 6379

  # Distributed tracing
  sleuth:
    enabled: ${TRACING_ENABLED:false}
  zipkin:
    baseUrl: http://tracing-service:9411/
