version: "3.2"

services:
  tracing-service:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    environment:
      TRACING_ENABLED: true

  storage-service:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_USER: malware
      MYSQL_DATABASE: ms_arch
      MYSQL_PASSWORD: userpassword
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin" , "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5

  cache-service:
    container_name: redis
    image: redis
    ports:
      - ":6379"
    environment:
      TRACING_ENABLED: true

  api-gateway:
    container_name: api-gateway
    image: api-gateway
    ports:
      - "8000:8000"
    build:
      context: api-gateway
    depends_on:
      storage-service:
        condition: service_healthy
    environment:
      HTTP2_ENABLED: true
      SSL_ENABLED:
      KEYSTORE_PASSWORD:
      KEYSTORE_PATH: /data/keystore.p12
    volumes:
      - ${KEYSTORE_PATH}:/data/keystore.p12

  auth-service:
    container_name: auth-service
    image: auth-service
    build:
      context: auth-service
    environment:
      TRACING_ENABLED: true
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "http://auth-service:8001/actuator/health"]
      interval: 5s
      timeout: 10s
      retries: 5
    depends_on:
      storage-service:
        condition: service_healthy

  product-service:
    container_name: product-service
    image: product-service
    build:
      context: product-service
    environment:
      TRACING_ENABLED: true
    depends_on:
      auth-service:
        condition: service_healthy
      storage-service:
        condition: service_healthy

volumes:
  mysql_data:
