version: "3.8"

services:
  tracing-service:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    deploy:
      resources:
        limits:
          memory: 500M
          cpus: "1"
    environment:
      TRACING_ENABLED: true

  storage-service:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_USER: malware
      MYSQL_DATABASE: ms_arch
      MYSQL_PASSWORD: userpassword
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin" , "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5

  cache-service:
    container_name: redis
    image: redis
    ports:
      - ":6379"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 100M
    environment:
      TRACING_ENABLED: "true"

  discovery-service:
    container_name: consul
    image: hashicorp/consul
    ports:
      - "8500:8500"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 500M

  api-gateway:
    image: api-gateway
    ports:
      - "8000:8000"
    build:
      context: api-gateway
    depends_on:
      - storage-service
    deploy:
      resources:
        limits:
          cpus: "1"
      restart_policy:
          condition: on-failure
          max_attempts: 10
          delay: 20s
    environment:
      SERVER_PORT: 8000
      HTTP2_ENABLED: false
      SSL_ENABLED: false
      KEYSTORE_PATH: /data/keystore.p12
      KEYSTORE_PASSWORD:
    volumes:
      - ./keystore.p12:/data/keystore.p12

  auth-service:
    image: auth-service
    build:
      context: auth-service
    ports:
      - ":8001"
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 500M
          cpus: "1"
      restart_policy:
        condition: on-failure
        max_attempts: 10
        delay: 20s
    healthcheck:
      test: [ "CMD", "curl", "--fail", "--silent", "http://auth-service:8001/actuator/health" ]
      interval: 5s
      timeout: 10s
      retries: 5
    depends_on:
      - storage-service
    environment:
      SERVER_PORT: 80
      TRACING_ENABLED: "true"

  product-service:
    image: product-service
    build:
      context: product-service
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 500M
          cpus: "1"
      restart_policy:
        condition: on-failure
        max_attempts: 10
        delay: 20s
    depends_on:
      - auth-service
      - storage-service
    healthcheck:
      test: [ "CMD", "curl", "--fail", "--silent", "http://auth-service:8001/actuator/health" ]
      interval: 5s
      timeout: 10s
      retries: 5
    environment:
      SERVER_PORT: 80
      TRACING_ENABLED: "true"

volumes:
  mysql_data:
    name: ms-arch
