server:
  port: 8000

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: http://auth-service:8001
          predicates:
            - Path=/users/**
        - id: PRODUCT-SERVICE
          uri: http://product-service:8002
          predicates:
            - Path=/products/**
