server:
  port: 8000
  ssl:
    enabled: ${SSL_ENABLED:false}
    key-store: ${KEYSTORE_PATH}
    key-store-password: ${KEYSTORE_PASSWORD:gokul656}
    key-store-type: PKCS12

spring:
  application:
    name: API-GATEWAY

  # Distributed tracing
  sleuth:
    enabled: ${TRACING_ENABLED:false}
  zipkin:
    baseUrl: http://tracing-service:9411/

  # Routes
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: http://auth-service:8001
          predicates:
            - Path=/users/**
        - id: PRODUCT-SERVICE
          uri: http://product-service:8002
          predicates:
            - Path=/products/**
