server:
  port: ${SERVER_PORT:8000}
  ssl:
    enabled: ${SSL_ENABLED:false}
    key-store: ${KEYSTORE_PATH}
    key-store-password: ${KEYSTORE_PASSWORD:gokul656}
    key-store-type: PKCS12

spring:
  application:
    name: api-gateway

  # Distributed tracing
  sleuth:
    enabled: ${TRACING_ENABLED:false}
  zipkin:
    baseUrl: http://tracing-service:9411/

  cloud:
    consul:
      host: discovery-service
      port: 8500
      config:
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/users/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
