spring:
  application:
    name: PRODUCT-SERVICE
  datasource:
    url: jdbc:mysql://storage-service/ms_arch?createDatabaseIfNotExist=true
    username: malware
    password: userpassword
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    generate-dll: true
    hibernate:
      ddl-auto: update
  web.origins: > 
    http://localhost:8001
server:
  port: 8002

